In [17]:
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import acquire
import prepare
from sklearn.tree import DecisionTreeClassifier, plot_tree, export_text
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score

In [18]:
titanic=acquire.get_titanic_data()

In [19]:
titanic=prepare.prep_titanic(titanic)

In [20]:
train, validate, test=prepare.my_train_test_split(titanic, 'survived')

In [21]:
train.head()

passenger_id  survived  pclass  sibsp  parch      fare  alone  sex_male  \
455           455         1       3      0      0    7.8958      1         1   
380           380         1       1      0      0  227.5250      1         0   
492           492         0       1      0      0   30.5000      1         1   
55             55         1       1      0      0   35.5000      1         1   
243           243         0       3      0      0    7.1250      1         1   

     embark_town_Queenstown  embark_town_Southampton  
455                       0                        0  
380                       0                        0  
492                       0                        1  
55                        0                        1  
243                       0                        1

In [22]:
titanic.head()

passenger_id  survived  pclass  sibsp  parch     fare  alone  sex_male  \
0             0         0       3      1      0   7.2500      0         1   
1             1         1       1      1      0  71.2833      0         0   
2             2         1       3      0      0   7.9250      1         0   
3             3         1       1      1      0  53.1000      0         0   
4             4         0       3      0      0   8.0500      1         1   

   embark_town_Queenstown  embark_town_Southampton  
0                       0                        1  
1                       0                        0  
2                       0                        1  
3                       0                        1  
4                       0                        1

In [23]:
train.head()

passenger_id  survived  pclass  sibsp  parch      fare  alone  sex_male  \
455           455         1       3      0      0    7.8958      1         1   
380           380         1       1      0      0  227.5250      1         0   
492           492         0       1      0      0   30.5000      1         1   
55             55         1       1      0      0   35.5000      1         1   
243           243         0       3      0      0    7.1250      1         1   

     embark_town_Queenstown  embark_town_Southampton  
455                       0                        0  
380                       0                        0  
492                       0                        1  
55                        0                        1  
243                       0                        1

In [24]:
x_train=train.drop(columns='survived')

In [25]:
x_train.head()

passenger_id  pclass  sibsp  parch      fare  alone  sex_male  \
455           455       3      0      0    7.8958      1         1   
380           380       1      0      0  227.5250      1         0   
492           492       1      0      0   30.5000      1         1   
55             55       1      0      0   35.5000      1         1   
243           243       3      0      0    7.1250      1         1   

     embark_town_Queenstown  embark_town_Southampton  
455                       0                        0  
380                       0                        0  
492                       0                        1  
55                        0                        1  
243                       0                        1

In [26]:
y_train=train.survived

In [27]:
clf=DecisionTreeClassifier(max_depth=3, random_state=123)

In [28]:
clf=clf.fit(x_train, y_train)

In [29]:
clf.score(x_train, y_train)

0.8146067415730337

In [31]:
y_pred=clf.predict(x_train)

In [32]:
confusion_matrix(y_train, y_pred)

array([[293,  36],
       [ 63, 142]])

In [37]:
pd.DataFrame(classification_report(y_train, y_pred, output_dict=True))

0           1  accuracy   macro avg  weighted avg
precision    0.823034    0.797753  0.814607    0.810393      0.813328
recall       0.890578    0.692683  0.814607    0.791630      0.814607
f1-score     0.855474    0.741514  0.814607    0.798494      0.811726
support    329.000000  205.000000  0.814607  534.000000    534.000000

In [38]:
clf1=DecisionTreeClassifier(max_depth=4, random_state=124)

In [39]:
clf1.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=4, random_state=124)

In [41]:
clf1.score(x_train, y_train)

0.8258426966292135

In [74]:
y_pred1=clf1.predict(x_train)

In [75]:
confusion_matrix(y_train, y_pred1)

array([[306,  23],
       [ 61, 144]])

In [76]:
pd.DataFrame(classification_report(y_train, y_pred1, output_dict=True))

0           1  accuracy   macro avg  weighted avg
precision    0.833787    0.862275  0.842697    0.848031      0.844724
recall       0.930091    0.702439  0.842697    0.816265      0.842697
f1-score     0.879310    0.774194  0.842697    0.826752      0.838957
support    329.000000  205.000000  0.842697  534.000000    534.000000

In [49]:
clf1=DecisionTreeClassifier(max_depth=5, random_state=125)

In [50]:
clf1.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=5, random_state=125)

In [52]:
clf1.score(x_train, y_train)

0.8426966292134831

In [54]:
y_pred1=clf1.predict(x_train)

In [56]:
confusion_matrix(y_train, y_pred1)

array([[306,  23],
       [ 61, 144]])

In [58]:
pd.DataFrame(classification_report(y_train, y_pred, output_dict=True))

0           1  accuracy   macro avg  weighted avg
precision    0.831461    0.814607  0.825843    0.823034      0.824991
recall       0.899696    0.707317  0.825843    0.803507      0.825843
f1-score     0.864234    0.757180  0.825843    0.810707      0.823136
support    329.000000  205.000000  0.825843  534.000000    534.000000

In [62]:
clf2=DecisionTreeClassifier(max_depth=5, random_state=126)

In [68]:
clf2.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=5, random_state=126)

In [64]:
clf2.score(x_train, y_train)

0.8426966292134831

In [71]:
y_pred2=clf2.predict(x_train)

In [72]:
confusion_matrix(y_train, y_pred)

array([[296,  33],
       [ 60, 145]])

In [73]:
pd.DataFrame(classification_report(y_train, y_pred1, output_dict=True))

0           1  accuracy   macro avg  weighted avg
precision    0.833787    0.862275  0.842697    0.848031      0.844724
recall       0.930091    0.702439  0.842697    0.816265      0.842697
f1-score     0.879310    0.774194  0.842697    0.826752      0.838957
support    329.000000  205.000000  0.842697  534.000000    534.000000

In [77]:
x_validate=validate.drop(columns='survived')
y_validate=validate.survived
x_test=test.drop(columns='survived')
y_test=test.survived

In [79]:
clf.score(x_validate, y_validate), clf1.score(x_validate, y_validate), clf2.score(x_validate, y_validate)

(0.7865168539325843, 0.7359550561797753, 0.7359550561797753)

In [82]:
test_acc=clf.predict(x_test)

In [85]:
pd.DataFrame(classification_report(y_test, test_acc,  output_dict=True))

0          1  accuracy   macro avg  weighted avg
precision    0.805085   0.754098  0.787709    0.779592      0.785431
recall       0.863636   0.666667  0.787709    0.765152      0.787709
f1-score     0.833333   0.707692  0.787709    0.770513      0.784902
support    110.000000  69.000000  0.787709  179.000000    179.000000