In [1]:
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import acquire
import prepare
from sklearn.tree import DecisionTreeClassifier, plot_tree, export_text
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

In [2]:
titanic=acquire.get_titanic_data()
titanic.head()

Unnamed: 0  passenger_id  survived  pclass     sex   age  sibsp  parch  \
0           0             0         0       3    male  22.0      1      0   
1           1             1         1       1  female  38.0      1      0   
2           2             2         1       3  female  26.0      0      0   
3           3             3         1       1  female  35.0      1      0   
4           4             4         0       3    male  35.0      0      0   

      fare embarked  class deck  embark_town  alone  
0   7.2500        S  Third  NaN  Southampton      0  
1  71.2833        C  First    C    Cherbourg      0  
2   7.9250        S  Third  NaN  Southampton      1  
3  53.1000        S  First    C  Southampton      0  
4   8.0500        S  Third  NaN  Southampton      1

In [3]:
titanic=prepare.prep_titanic(titanic)
titanic.head()

passenger_id  survived  pclass   age  sibsp  parch     fare  alone  \
0             0         0       3  22.0      1      0   7.2500      0   
1             1         1       1  38.0      1      0  71.2833      0   
2             2         1       3  26.0      0      0   7.9250      1   
3             3         1       1  35.0      1      0  53.1000      0   
4             4         0       3  35.0      0      0   8.0500      1   

   sex_male  embark_town_Queenstown  embark_town_Southampton  
0         1                       0                        1  
1         0                       0                        0  
2         0                       0                        1  
3         0                       0                        1  
4         1                       0                        1

In [4]:
train, validate, test=prepare.my_train_test_split(titanic, 'survived')
titanic.head()

passenger_id  survived  pclass   age  sibsp  parch     fare  alone  \
0             0         0       3  22.0      1      0   7.2500      0   
1             1         1       1  38.0      1      0  71.2833      0   
2             2         1       3  26.0      0      0   7.9250      1   
3             3         1       1  35.0      1      0  53.1000      0   
4             4         0       3  35.0      0      0   8.0500      1   

   sex_male  embark_town_Queenstown  embark_town_Southampton  
0         1                       0                        1  
1         0                       0                        0  
2         0                       0                        1  
3         0                       0                        1  
4         1                       0                        1

In [5]:
train.head()

passenger_id  survived  pclass   age  sibsp  parch      fare  alone  \
455           455         1       3  29.0      0      0    7.8958      1   
380           380         1       1  42.0      0      0  227.5250      1   
492           492         0       1  55.0      0      0   30.5000      1   
55             55         1       1  28.0      0      0   35.5000      1   
243           243         0       3  22.0      0      0    7.1250      1   

     sex_male  embark_town_Queenstown  embark_town_Southampton  
455         1                       0                        0  
380         0                       0                        0  
492         1                       0                        1  
55          1                       0                        1  
243         1                       0                        1

In [6]:
titanic.head()

passenger_id  survived  pclass   age  sibsp  parch     fare  alone  \
0             0         0       3  22.0      1      0   7.2500      0   
1             1         1       1  38.0      1      0  71.2833      0   
2             2         1       3  26.0      0      0   7.9250      1   
3             3         1       1  35.0      1      0  53.1000      0   
4             4         0       3  35.0      0      0   8.0500      1   

   sex_male  embark_town_Queenstown  embark_town_Southampton  
0         1                       0                        1  
1         0                       0                        0  
2         0                       0                        1  
3         0                       0                        1  
4         1                       0                        1

In [7]:
train.head()

passenger_id  survived  pclass   age  sibsp  parch      fare  alone  \
455           455         1       3  29.0      0      0    7.8958      1   
380           380         1       1  42.0      0      0  227.5250      1   
492           492         0       1  55.0      0      0   30.5000      1   
55             55         1       1  28.0      0      0   35.5000      1   
243           243         0       3  22.0      0      0    7.1250      1   

     sex_male  embark_town_Queenstown  embark_town_Southampton  
455         1                       0                        0  
380         0                       0                        0  
492         1                       0                        1  
55          1                       0                        1  
243         1                       0                        1

In [8]:
x_train=train.drop(columns='survived')

In [9]:
x_train.head()

passenger_id  pclass   age  sibsp  parch      fare  alone  sex_male  \
455           455       3  29.0      0      0    7.8958      1         1   
380           380       1  42.0      0      0  227.5250      1         0   
492           492       1  55.0      0      0   30.5000      1         1   
55             55       1  28.0      0      0   35.5000      1         1   
243           243       3  22.0      0      0    7.1250      1         1   

     embark_town_Queenstown  embark_town_Southampton  
455                       0                        0  
380                       0                        0  
492                       0                        1  
55                        0                        1  
243                       0                        1

In [10]:
y_train=train.survived

In [11]:
clf=DecisionTreeClassifier(max_depth=3, random_state=123)

In [12]:
clf=clf.fit(x_train, y_train)

In [13]:
clf.score(x_train, y_train)

0.8202247191011236

In [14]:
y_pred=clf.predict(x_train)

In [15]:
confusion_matrix(y_train, y_pred)

array([[296,  33],
       [ 63, 142]])

In [16]:
pd.DataFrame(classification_report(y_train, y_pred, output_dict=True))

0           1  accuracy   macro avg  weighted avg
precision    0.824513    0.811429  0.820225    0.817971      0.819490
recall       0.899696    0.692683  0.820225    0.796189      0.820225
f1-score     0.860465    0.747368  0.820225    0.803917      0.817048
support    329.000000  205.000000  0.820225  534.000000    534.000000

In [17]:
clf1=DecisionTreeClassifier(max_depth=4, random_state=124)

In [18]:
clf1.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=4, random_state=124)

In [19]:
clf1.score(x_train, y_train)

0.8352059925093633

In [20]:
y_pred1=clf1.predict(x_train)

In [21]:
confusion_matrix(y_train, y_pred1)

array([[293,  36],
       [ 52, 153]])

In [22]:
pd.DataFrame(classification_report(y_train, y_pred1, output_dict=True))

0           1  accuracy   macro avg  weighted avg
precision    0.849275    0.809524  0.835206    0.829400      0.834015
recall       0.890578    0.746341  0.835206    0.818459      0.835206
f1-score     0.869436    0.776650  0.835206    0.823043      0.833816
support    329.000000  205.000000  0.835206  534.000000    534.000000

In [23]:
clf1=DecisionTreeClassifier(max_depth=5, random_state=125)

In [24]:
clf1.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=5, random_state=125)

In [25]:
clf1.score(x_train, y_train)

0.8595505617977528

In [26]:
y_pred1=clf1.predict(x_train)

In [27]:
confusion_matrix(y_train, y_pred1)

array([[315,  14],
       [ 61, 144]])

In [28]:
pd.DataFrame(classification_report(y_train, y_pred, output_dict=True))

0           1  accuracy   macro avg  weighted avg
precision    0.824513    0.811429  0.820225    0.817971      0.819490
recall       0.899696    0.692683  0.820225    0.796189      0.820225
f1-score     0.860465    0.747368  0.820225    0.803917      0.817048
support    329.000000  205.000000  0.820225  534.000000    534.000000

In [29]:
clf2=DecisionTreeClassifier(max_depth=5, random_state=126)

In [30]:
clf2.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=5, random_state=126)

In [31]:
clf2.score(x_train, y_train)

0.8595505617977528

In [32]:
y_pred2=clf2.predict(x_train)

In [33]:
confusion_matrix(y_train, y_pred)

array([[296,  33],
       [ 63, 142]])

In [34]:
pd.DataFrame(classification_report(y_train, y_pred1, output_dict=True))

0           1  accuracy   macro avg  weighted avg
precision    0.837766    0.911392  0.859551    0.874579      0.866031
recall       0.957447    0.702439  0.859551    0.829943      0.859551
f1-score     0.893617    0.793388  0.859551    0.843503      0.855140
support    329.000000  205.000000  0.859551  534.000000    534.000000

In [35]:
x_validate=validate.drop(columns='survived')
y_validate=validate.survived
x_test=test.drop(columns='survived')
y_test=test.survived

In [36]:
clf.score(x_validate, y_validate), clf1.score(x_validate, y_validate), clf2.score(x_validate, y_validate)

(0.8146067415730337, 0.7921348314606742, 0.7921348314606742)

In [37]:
test_acc=clf.predict(x_test)

In [38]:
pd.DataFrame(classification_report(y_test, test_acc,  output_dict=True))

0          1  accuracy   macro avg  weighted avg
precision    0.803279   0.789474  0.798883    0.796376      0.797957
recall       0.890909   0.652174  0.798883    0.771542      0.798883
f1-score     0.844828   0.714286  0.798883    0.779557      0.794507
support    110.000000  69.000000  0.798883  179.000000    179.000000

In [39]:
rf=RandomForestClassifier(min_samples_leaf=1, max_depth=10)

In [40]:
rf.fit(x_train, y_train)

RandomForestClassifier(max_depth=10)

In [41]:
rf.score(x_train, y_train)

0.9700374531835206

In [42]:
y_pred4=rf.predict(x_train)

In [43]:
confusion_matrix(y_train, y_pred4)

array([[329,   0],
       [ 16, 189]])

In [44]:
pd.DataFrame(classification_report(y_train, y_pred4, output_dict=True))

0           1  accuracy   macro avg  weighted avg
precision    0.953623    1.000000  0.970037    0.976812      0.971427
recall       1.000000    0.921951  0.970037    0.960976      0.970037
f1-score     0.976261    0.959391  0.970037    0.967826      0.969785
support    329.000000  205.000000  0.970037  534.000000    534.000000

In [45]:
rf1=RandomForestClassifier(min_samples_leaf=2, max_depth=9)

In [46]:
rf1.fit(x_train, y_train)

RandomForestClassifier(max_depth=9, min_samples_leaf=2)

In [47]:
rf1.score(x_train, y_train)

0.9363295880149812

In [48]:
y_pred5=rf1.predict(x_train)

In [49]:
confusion_matrix(y_train, y_pred5)

array([[324,   5],
       [ 29, 176]])

In [50]:
pd.DataFrame(classification_report(y_train, y_pred5, output_dict=True))

0           1  accuracy   macro avg  weighted avg
precision    0.917847    0.972376   0.93633    0.945111       0.93878
recall       0.984802    0.858537   0.93633    0.921670       0.93633
f1-score     0.950147    0.911917   0.93633    0.931032       0.93547
support    329.000000  205.000000   0.93633  534.000000     534.00000

In [51]:
rf.score(x_validate, y_validate), rf1.score(x_validate, y_validate)

(0.8089887640449438, 0.8146067415730337)

In [52]:
test_acc_rf=rf1.predict(x_test)

In [53]:
pd.DataFrame(classification_report(y_test, test_acc_rf, output_dict=True))

0          1  accuracy   macro avg  weighted avg
precision    0.837607   0.806452  0.826816    0.822029      0.825597
recall       0.890909   0.724638  0.826816    0.807773      0.826816
f1-score     0.863436   0.763359  0.826816    0.813397      0.824859
support    110.000000  69.000000  0.826816  179.000000    179.000000

In [54]:
knn=KNeighborsClassifier()

In [55]:
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [56]:
knn.score(x_train, y_train)

0.7565543071161048

In [57]:
knn_pred=knn.predict(x_train)

In [58]:
confusion_matrix(y_train, knn_pred)

array([[289,  40],
       [ 90, 115]])

In [59]:
pd.DataFrame(classification_report(y_train, knn_pred, output_dict=True))

0           1  accuracy   macro avg  weighted avg
precision    0.762533    0.741935  0.756554    0.752234      0.754626
recall       0.878419    0.560976  0.756554    0.719698      0.756554
f1-score     0.816384    0.638889  0.756554    0.727637      0.748245
support    329.000000  205.000000  0.756554  534.000000    534.000000

In [60]:
knn1=KNeighborsClassifier(n_neighbors=10)

In [61]:
knn1.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=10)

In [62]:
knn1.score(x_train, y_train)

0.702247191011236

In [63]:
knn1_pred=knn1.predict(x_train)

In [64]:
confusion_matrix(y_train, knn1_pred)

array([[304,  25],
       [134,  71]])

In [65]:
pd.DataFrame(classification_report(y_train, knn1_pred, output_dict=True))

0           1  accuracy   macro avg  weighted avg
precision    0.694064    0.739583  0.702247    0.716824      0.711539
recall       0.924012    0.346341  0.702247    0.635177      0.702247
f1-score     0.792699    0.471761  0.702247    0.632230      0.669492
support    329.000000  205.000000  0.702247  534.000000    534.000000

In [66]:
knn2=KNeighborsClassifier(n_neighbors=20)

In [67]:
knn2.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=20)

In [68]:
knn2.score(x_train, y_train)

0.6816479400749064

In [69]:
knn2_pred=knn2.predict(x_train)

In [70]:
confusion_matrix(y_train, knn2_pred)

array([[312,  17],
       [153,  52]])

In [71]:
pd.DataFrame(classification_report(y_train, knn2_pred, output_dict=True))

0           1  accuracy   macro avg  weighted avg
precision    0.670968    0.753623  0.681648    0.712295      0.702699
recall       0.948328    0.253659  0.681648    0.600993      0.681648
f1-score     0.785894    0.379562  0.681648    0.582728      0.629905
support    329.000000  205.000000  0.681648  534.000000    534.000000

In [72]:
knn.score(x_validate, y_validate), knn1.score(x_validate, y_validate), knn2.score(x_validate, y_validate)

(0.651685393258427, 0.5955056179775281, 0.651685393258427)

In [73]:
test_accuracy_knn=knn2.predict(x_test)

In [74]:
confusion_matrix(y_test, test_accuracy_knn)

array([[101,   9],
       [ 45,  24]])

In [75]:
pd.DataFrame(classification_report(y_test, test_accuracy_knn, output_dict=True))

0          1  accuracy   macro avg  weighted avg
precision    0.691781   0.727273  0.698324    0.709527      0.705462
recall       0.918182   0.347826  0.698324    0.633004      0.698324
f1-score     0.789062   0.470588  0.698324    0.629825      0.666299
support    110.000000  69.000000  0.698324  179.000000    179.000000

In [76]:
baseline_pred=round((train.survived==0).mean(), 2)
baseline_pred

0.62

In [77]:
x_train.head()

passenger_id  pclass   age  sibsp  parch      fare  alone  sex_male  \
455           455       3  29.0      0      0    7.8958      1         1   
380           380       1  42.0      0      0  227.5250      1         0   
492           492       1  55.0      0      0   30.5000      1         1   
55             55       1  28.0      0      0   35.5000      1         1   
243           243       3  22.0      0      0    7.1250      1         1   

     embark_town_Queenstown  embark_town_Southampton  
455                       0                        0  
380                       0                        0  
492                       0                        1  
55                        0                        1  
243                       0                        1

In [80]:
logit=LogisticRegression(random_state=1234)


In [89]:
feauts=x_train[['age', 'fare', 'pclass']]
logit.fit(feauts, y_train)
logit.score(feauts, y_train)


0.7059925093632958

In [91]:
logitr=logit.predict(feauts)

In [93]:
confusion_matrix(y_train, logitr)

array([[287,  42],
       [115,  90]])

In [97]:
pd.DataFrame(classification_report(y_train, logitr, output_dict=True))

0           1  accuracy   macro avg  weighted avg
precision    0.713930    0.681818  0.705993    0.697874      0.701603
recall       0.872340    0.439024  0.705993    0.655682      0.705993
f1-score     0.785226    0.534125  0.705993    0.659675      0.688829
support    329.000000  205.000000  0.705993  534.000000    534.000000

In [113]:
feauts1=x_train[['age', 'pclass', 'sex_male', 'fare']]

In [114]:
logit1=LogisticRegression(random_state=1234)

In [115]:
logit1.fit(feauts1, y_train)

LogisticRegression(random_state=1234)

In [116]:
logit1.score(feauts1, y_train)

0.799625468164794

In [117]:
logitr1=logit1.predict(feauts1)

In [118]:
pd.DataFrame(classification_report(logitr1, y_train, output_dict=True))

0           1  accuracy   macro avg  weighted avg
precision    0.841945    0.731707  0.799625    0.786826      0.800245
recall       0.834337    0.742574  0.799625    0.788456      0.799625
f1-score     0.838124    0.737101  0.799625    0.787612      0.799909
support    332.000000  202.000000  0.799625  534.000000    534.000000

In [120]:
feauts2=x_train[['alone', 'sex_male', 'age']]

In [121]:
logit2=LogisticRegression(random_state=1234)

In [122]:
logit2.fit(feauts2, y_train)

LogisticRegression(random_state=1234)

In [123]:
logit2.score(feauts2, y_train)

0.7921348314606742

In [124]:
logitr2=logit2.predict(feauts2)

In [125]:
confusion_matrix(y_train, logitr2)

array([[283,  46],
       [ 65, 140]])

In [127]:
pd.DataFrame(classification_report(y_train, logitr2, output_dict=True))

0           1  accuracy   macro avg  weighted avg
precision    0.813218    0.752688  0.792135    0.782953      0.789981
recall       0.860182    0.682927  0.792135    0.771555      0.792135
f1-score     0.836041    0.716113  0.792135    0.776077      0.790001
support    329.000000  205.000000  0.792135  534.000000    534.000000

In [144]:
logit.score(x_validate[['age', 'fare', 'pclass']], y_validate), logit1.score(x_validate[['age', 'pclass', 'sex_male', 'fare']], y_validate), logit2.score(x_validate[['alone', 'sex_male', 'age']], y_validate)


(0.6966292134831461, 0.7865168539325843, 0.7752808988764045)

In [147]:
test_accr=logit1.predict(x_test[['age', 'pclass', 'sex_male', 'fare']])

In [149]:
confusion_matrix(y_test, test_acc)

array([[98, 12],
       [24, 45]])

In [151]:
pd.DataFrame(classification_report(y_test, test_accr, output_dict=True))

0          1  accuracy   macro avg  weighted avg
precision    0.834862   0.728571  0.793296    0.781717      0.793890
recall       0.827273   0.739130  0.793296    0.783202      0.793296
f1-score     0.831050   0.733813  0.793296    0.782432      0.793568
support    110.000000  69.000000  0.793296  179.000000    179.000000